### ISSUE TITLE
Restart IIS in production returns error if user is logged in 

### ISSUE THREAD

**Issue by dimkoug** [microsoftgraph/aspnetcore-connect-sample#58]
I build an application and use the microsoft graph for login and logout. When a user  is logged in via microsoft graph and in the same time i restart the iis server.If the user refersh the page the token is  invalid and returns an error page.

What steps can i do, so when i restart the iis , the logged in user refreshes the token automatically via the  microsoft graph api

**Comment by mark-szabo** [comment]
There are two types of tokens in this case: an access token (what you are using to call Graph) and a refresh token. Your tokens are stored in memory (because the tokens get cleared when you restart IIS).
If you clear the token cache (eg. by restarting IIS), you clear the refresh tokens as well, so you won't be able to just refresh the tokens, but will need to do a full re-authentication.
I'd advise to store the tokens in a persistent token cache (eg File).

- you will need a TokenCacheHelper like this: https://github.com/mark-szabo/teams-presence-monitor/blob/master/TeamsPresenceMonitor/TokenCacheHelper.cs
- and in the GraphAuthProvider when you create the app just call this: `TokenCacheHelper.EnableSerialization(_app.UserTokenCache);`

**Comment by dimkoug** [comment]
Thanks the code  works in the development mode but in production it generates error , i suspect  iis dosen't have read/write permissions to create the bin3 file.

        public GraphAuthProvider(IConfiguration configuration)
        {
            var azureOptions = new AzureAdOptions();
            configuration.Bind("AzureAd", azureOptions);

            // More info about MSAL Client Applications: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications
            _app = ConfidentialClientApplicationBuilder.Create(azureOptions.ClientId)
                    .WithClientSecret(azureOptions.ClientSecret)
                    .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount)
                    .WithRedirectUri(azureOptions.BaseUrl + azureOptions.CallbackPath)
                    .Build();
            TokenCacheHelper.EnableSerialization(_app.UserTokenCache);

            Authority = _app.Authority;

            _scopes = azureOptions.GraphScopes.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
        }

**Comment by dimkoug** [comment]
based on tha answer https://stackoverflow.com/a/53054375/924300  i fixed it , thanks a lot for the code, it works !!!!
